/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recommendBear;

import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author shane
 */
public class AppUI extends javax.swing.JFrame {

    private String username, project;
    private int selectedGenger, bornYear, thisYear;
    private double height, weight, higherExercise, enterTime;
    private boolean wasSetting;
    private double protein, fat, carbohydrate;
    FoodList foodList = new FoodList();

    DBconnct conn;
    Statement sta = null;

    /**
     * Creates new form AppUI
     */
    public AppUI() {
        initComponents();
        conn = new DBconnct();
        sta = conn.getSta();

        wasSetting = false;
        init_areaText();
        thisYear = 2019;
        higherExercise = 0.5;

        //System.out.println( conn.getFood(conn.getRandomFoodNum("乳品類")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        totalTimeLabel = new javax.swing.JLabel();
        jTextField_enterTime = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_result = new javax.swing.JTextArea();
        totalTimeLabel1 = new javax.swing.JLabel();
        jComboBox_exerciseLevel = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_name1 = new javax.swing.JLabel();
        jLabel_name2 = new javax.swing.JLabel();
        jLabel_name3 = new javax.swing.JLabel();
        jLabel_name4 = new javax.swing.JLabel();
        jLabel_showProtion = new javax.swing.JLabel();
        jRadioButton_boy = new javax.swing.JRadioButton();
        jRadioButton_girl = new javax.swing.JRadioButton();
        jButton_saveInfo = new javax.swing.JButton();
        jButton_setExample = new javax.swing.JButton();
        jTextField_name = new javax.swing.JTextField();
        jTextField_height = new javax.swing.JTextField();
        jTextField_weight = new javax.swing.JTextField();
        jTextField_bornYear = new javax.swing.JTextField();
        jComboBox_projects = new javax.swing.JComboBox<>();
        jSlider1 = new javax.swing.JSlider();
        jLabel_name6 = new javax.swing.JLabel();
        jLabel_name7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("熊熊吃甚麼?");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        totalTimeLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        totalTimeLabel.setText("進場時間");

        jTextField_enterTime.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextField_enterTime.setToolTipText("輸入本次進場的分鐘數");

        jButton_search.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jButton_search.setText("查詢健身菜單");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jTextArea_result.setColumns(20);
        jTextArea_result.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextArea_result.setRows(5);
        jScrollPane1.setViewportView(jTextArea_result);

        totalTimeLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        totalTimeLabel1.setText("運動量");

        jComboBox_exerciseLevel.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jComboBox_exerciseLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "輕度", "中度", "高度", "密集" }));
        jComboBox_exerciseLevel.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(totalTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_enterTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalTimeLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_exerciseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTimeLabel)
                    .addComponent(jTextField_enterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalTimeLabel1)
                    .addComponent(jComboBox_exerciseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("菜單推薦", jPanel1);

        jLabel_name.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name.setText("姓名");

        jLabel_name1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name1.setText("身高(Cm)");

        jLabel_name2.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name2.setText("體重(Kg)");

        jLabel_name3.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name3.setText("性別");

        jLabel_name4.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name4.setText("出生年");

        jLabel_showProtion.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_showProtion.setText("50%");

        buttonGroup1.add(jRadioButton_boy);
        jRadioButton_boy.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jRadioButton_boy.setSelected(true);
        jRadioButton_boy.setText("我是帥哥");

        buttonGroup1.add(jRadioButton_girl);
        jRadioButton_girl.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jRadioButton_girl.setText("我是美女");

        jButton_saveInfo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jButton_saveInfo.setText("儲存會員資料");
        jButton_saveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveInfoActionPerformed(evt);
            }
        });

        jButton_setExample.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jButton_setExample.setText("匯入範例");
        jButton_setExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_setExampleActionPerformed(evt);
            }
        });

        jTextField_name.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextField_name.setToolTipText("輸入本次進場的分鐘數");

        jTextField_height.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextField_height.setToolTipText("輸入本次進場的分鐘數");

        jTextField_weight.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextField_weight.setToolTipText("輸入本次進場的分鐘數");

        jTextField_bornYear.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextField_bornYear.setToolTipText("輸入本次進場的分鐘數");

        jComboBox_projects.setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        jComboBox_projects.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "正常飲食", "增肌飲食", "減脂飲食" }));

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel_name6.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name6.setText("方案選擇");

        jLabel_name7.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel_name7.setText("重訓比例");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_boy)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_girl))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_name4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_name6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_name7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_showProtion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_weight)
                                        .addComponent(jTextField_height)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jTextField_bornYear)
                                            .addGap(17, 17, 17))
                                        .addComponent(jComboBox_projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton_setExample, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jButton_saveInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name3)
                    .addComponent(jRadioButton_boy)
                    .addComponent(jRadioButton_girl))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name1)
                    .addComponent(jTextField_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name2)
                    .addComponent(jTextField_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name4)
                    .addComponent(jTextField_bornYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name6))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_showProtion)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_setExample, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_saveInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("會員資料設定", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // TODO add your handling code here:
        if (wasSetting) {
            String resultOutput;
            String genderAdd = "先生";
            if (!jTextField_enterTime.getText().equals("")) {
                if (this.selectedGenger == 2) {
                    genderAdd = "小姐";
                }
                this.enterTime = Integer.parseInt(jTextField_enterTime.getText());
                String sentenceFormat = "你好，%s" + genderAdd + "\n身高=%.1f, 體重=%.1f, 年紀=%d, 選擇方案=%s";
                resultOutput = String.format(sentenceFormat, this.username, this.height, this.weight, this.thisYear - this.bornYear, this.project);
                jTextArea_result.setText(resultOutput);
                jTextArea_result.append(String.format("\n%.1f\n", this.getBMR()));
                jTextArea_result.append(String.format("\n%.1f\n", this.getTDEE(this.getBMR())));
                computeConsist(this.getTDEE(this.getBMR()));
                //
                make_food_list();
            } else {
                JOptionPane.showMessageDialog(null, "請輸入入場時間", "提示", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "請進行會員資料設定", "提示", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_searchActionPerformed


    private void jButton_setExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_setExampleActionPerformed
        // TODO add your handling code here:
        jTextField_name.setText("大熊熊");
        jRadioButton_boy.setSelected(true);
        jTextField_height.setText("170");
        jTextField_weight.setText("80");
        jTextField_bornYear.setText("1999");
        jComboBox_projects.setSelectedIndex(1);
    }//GEN-LAST:event_jButton_setExampleActionPerformed

    private void jButton_saveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveInfoActionPerformed
        // TODO add your handling code here:
        this.username = jTextField_name.getText();
        if (jRadioButton_boy.isSelected()) {
            this.selectedGenger = 1; //男生
        } else {
            this.selectedGenger = 2; //女生
        }
        this.height = Double.parseDouble(jTextField_height.getText());
        this.weight = Double.parseDouble(jTextField_weight.getText());
        this.bornYear = Integer.parseInt(jTextField_bornYear.getText());
        this.project = jComboBox_projects.getItemAt(jComboBox_projects.getSelectedIndex());
        JOptionPane.showMessageDialog(null, "儲存完成", "提示", JOptionPane.INFORMATION_MESSAGE);
        wasSetting = true;
    }//GEN-LAST:event_jButton_saveInfoActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        init_areaText();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jLabel_showProtion.setText(String.valueOf(jSlider1.getValue()) + "%");
        higherExercise = (double) jSlider1.getValue() / 100.0;
    }//GEN-LAST:event_jSlider1StateChanged

    private void init_areaText() {
        if (wasSetting) {
            jTextArea_result.setText("請在上方欄位\n設定本次進場的時間(分鐘)與運動量");
        } else {
            jTextArea_result.setText("歡迎使用\n請先在個人資料進行初始設定");
        }
    }

    private double getBMR() {
        //TheMifflinStJeorEquation公式
        double bmr = 10 * this.weight + 6.25 * this.height - 5 * (this.thisYear - this.bornYear);
        if (this.selectedGenger == 1) { //男生
            bmr += 5;
        } else {
            bmr -= 151;
        }

        return bmr;
    }

    private double getTDEE(double bmr) {
        int exerciseLevel = jComboBox_exerciseLevel.getSelectedIndex();
        double tdee = bmr;
        //計算總消耗量
        switch (exerciseLevel) {
            case 0:
                tdee = tdee * 1.375; //輕量
                break;
            case 1:
                tdee = tdee * 1.55;
                break;
            case 2:
                tdee = tdee * 1.725;
                break;
            case 3:
                tdee = tdee * 1.9; //密集
                break;
        }

        //設定目標
        if (project.equals("增肌飲食")) {
            tdee += 300;
        } else if (project.equals("減脂飲食")) {
            tdee -= 300;
        }

        //補運動時間的估計熱量
        tdee += (5 * enterTime * higherExercise);
        tdee += (2.5 * enterTime * (1 - higherExercise));

        return tdee;
    }

    private void computeConsist(double tdee) {
        if (project.equals("增肌飲食")) {
            protein = tdee * 0.2 / 4 / 3;
            fat = tdee * 0.2 / 9 / 3;
            carbohydrate = tdee * 0.6 / 4 / 3;
        } else if (project.equals("減脂飲食")) {
            protein = tdee * 0.3 / 4 / 3;
            fat = tdee * 0.25 / 9 / 3;
            carbohydrate = tdee * 0.45 / 4 / 3;
        } else {
            protein = tdee * 0.15 / 4 / 3;
            fat = tdee * 0.3 / 9 / 3;
            carbohydrate = tdee * 0.55 / 4 / 3;
        }
        foodList.setProtein(protein); //先把原始要存的複製一份到清單 做最後的清點用
        foodList.setFat(fat);
        foodList.setCarbohydrate(carbohydrate);
    }

    private void make_food_list() {
        boolean makeGrasp = true;
        int current = -1;
        int noGraspCount = 0;

        while (makeGrasp) {
            Food food;

            switch (current) {
                case -1: //乳品類
                    food = conn.getFood(conn.getRandomFoodNum("乳品類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit());
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());

                    }
                    break;
                case 0:
                    food = conn.getFood(conn.getRandomFoodNum("堅果類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit()); //放食物與數量
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());

                    }
                    break;

                case 1:
                    food = conn.getFood(conn.getRandomFoodNum("全榖雜糧類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit()); //放食物與數量
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());

                    } else {
                        noGraspCount += 1;
                    }
                    break;
                case 2:
                    food = conn.getFood(conn.getRandomFoodNum("肉類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit()); //放食物與數量
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());

                    } else {
                        noGraspCount += 1;
                    }
                    break;
                case 3:
                    food = conn.getFood(conn.getRandomFoodNum("蛋類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit()); //放食物與數量
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());
    
                    } else {
                        noGraspCount += 1;
                    }
                    break;
                case 4:
                    food = conn.getFood(conn.getRandomFoodNum("蔬菜類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit()); //放食物與數量
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());

                    } else {
                        noGraspCount += 1;
                    }
                    break;
                case 5:
                    food = conn.getFood(conn.getRandomFoodNum("水果類"));
                    if (Food.checkPut(food, protein, fat, carbohydrate)) { //如果還夠取
                        this.foodList.add_food(food, food.getLimit()); //放食物與數量
                        protein -= (food.getProtein() * food.getLimit());
                        fat -= (food.getFat() * food.getLimit());
                        carbohydrate -= (food.getCarbohydrate() * food.getLimit());
           
                    } else {
                        noGraspCount += 1;
                    }
                    break;
                case 6:
                    if (noGraspCount != 5) {
                        noGraspCount = 0;
                    }else{
                        makeGrasp = false; //全部都取不了 就跳出
                        this.foodList.showAll();
                    }
                    break;
            }

            if (current != 6) {
                current += 1;
            } else {
                current = 1; //回到3 跳過牛奶與堅果
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_saveInfo;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_setExample;
    private javax.swing.JComboBox<String> jComboBox_exerciseLevel;
    private javax.swing.JComboBox<String> jComboBox_projects;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JLabel jLabel_name2;
    private javax.swing.JLabel jLabel_name3;
    private javax.swing.JLabel jLabel_name4;
    private javax.swing.JLabel jLabel_name6;
    private javax.swing.JLabel jLabel_name7;
    private javax.swing.JLabel jLabel_showProtion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_boy;
    private javax.swing.JRadioButton jRadioButton_girl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea_result;
    private javax.swing.JTextField jTextField_bornYear;
    private javax.swing.JTextField jTextField_enterTime;
    private javax.swing.JTextField jTextField_height;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_weight;
    private javax.swing.JLabel totalTimeLabel;
    private javax.swing.JLabel totalTimeLabel1;
    // End of variables declaration//GEN-END:variables
}
